name: Build docs
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
          build-command: 'sphinx-build -b html . _build/html -W --keep-going -n'
