name: Build docs
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "pip install Sphinx==4.2.0 recommonmark==0.7.1"
          docs-folder: "docs/"
          build-command: 'make html SPHINXOPTS="-W --keep-going -n"'
