name: Build docs
on:
  pull_request:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # clone full repo to get last-updated dates
      - uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "sudo apt-get install -y git"
          docs-folder: "docs/"
          build-command: 'sphinx-build -b html . _build/html -W'
