name: Run tests Windows
on:
  push:

jobs:
  test:
    name: Test runtime
    runs-on: windows-2019
    steps:
      # Disable autocrlf setting, otherwise scalalib patches might not be possible to apply
      - name: Setup git config
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-setup-env
        id: setup
        with:
          scala-version: 3

      - name: Test runtime None GC
        run:
          sbt sandbox3/run
        shell: cmd